### ISSUE TITLE
如何取消启动自启？是因为hook的原因吗？

### ISSUE THREAD

**Issue by Dunkelicht** [yanjinhuagood/SoftwareHelper#5]
请问是怎么实现启动自启动的，如何取消呢？ 我愣是没找到如何实现的，请指点，非常感谢！

**Comment by yanjinhuagood** [comment]
win10 可以通过“任务管理器”中的”启动“中找到 “SoftwareHelper” 右键“关闭”即可。
win7  通过 命令 “msconfig” 进入 tab页 “启动”关闭开机启动。

**Comment by Dunkelicht** [comment]
> win10 可以通过“任务管理器”中的”启动“中找到 “SoftwareHelper” 右键“关闭”即可。 win7 通过 命令 “msconfig” 进入 tab页 “启动”关闭开机启动。

谢谢回复，请问是通过修改注册表哪里实现的？ 我的开发环境是Server 2019，任务管理器没有启动tab。

**Comment by Dunkelicht** [comment]
主要是我通过autoruns也没找到启动项目在哪里？

**Comment by yanjinhuagood** [comment]
> > win10 可以通过“任务管理器”中的”启动“中找到 “SoftwareHelper” 右键“关闭”即可。 win7 通过 命令 “msconfig” 进入 tab页 “启动”关闭开机启动。
> 
> 谢谢回复，请问是通过修改注册表哪里实现的？ 我的开发环境是Server 2019，任务管理器没有启动tab。
您好，非常感谢您的使用，并积极反馈。按理删除目录下创建的 
"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\SoftwareHelper.url"就行。
这个下一把版本做成可设置再托盘处增加“开机启动”和“开机不启动”操作。

**Comment by Dunkelicht** [comment]
非常感谢！ 

最后查到是在：
%appdata%\Microsoft\Windows\Start Menu\Programs\Startup

不同系统有不同的位置吧

**Comment by yanjinhuagood** [comment]
不客气，找到就好。欢迎关注组织 https://github.com/WPFDevelopersOrg/WPFDevelopers

**Comment by Dunkelicht** [comment]
> 不客气，找到就好。欢迎关注组织 https://github.com/WPFDevelopersOrg/WPFDevelopers

再次感谢 已经关注

**Comment by yanjinhuagood** [comment]
请下载最新版@Dunkelicht
